### ISSUE TITLE
Формат сохраненных соединений (ctor) сделать текстовым

### ISSUE THREAD

**Issue by x09** [ekorneechev/Connector#39]
Какой сакральный смысл делать его бинарным. Сейчас имею какой-то глюк, сохраненные соединения подключаются, но редактировать не дает. И посмотреть внутрь нельзя.

**Comment by ekorneechev** [comment]
> Сейчас имею какой-то глюк, сохраненные соединения подключаются, но редактировать не дает. И посмотреть внутрь нельзя.

вот здесь по-подробнее. ошибка выдается? возможно что-то есть в логах.

**Comment by ekorneechev** [comment]
> Какой сакральный смысл делать его бинарным.

Если б я помнил, что было в моей голове в далеком 2014...

**Comment by x09** [comment]
> > Сейчас имею какой-то глюк, сохраненные соединения подключаются, но редактировать не дает. И посмотреть внутрь нельзя.
> 
> вот здесь по-подробнее. ошибка выдается? возможно что-то есть в логах.

в багзилле альтовской.. сказали вы туда часто глядите #36757

**Comment by ekorneechev** [comment]
> > > Сейчас имею какой-то глюк, сохраненные соединения подключаются, но редактировать не дает. И посмотреть внутрь нельзя.
> > 
> > 
> > вот здесь по-подробнее. ошибка выдается? возможно что-то есть в логах.
> 
> в багзилле альтовской.. сказали вы туда часто глядите #36757

Это fixed.

**Comment by ekorneechev** [comment]
По текстовому формату подумаю к релизу 1.8.6

**Comment by x09** [comment]
вот сегодня опять столкнулся, что надо заиметь шаблон соединения и менять там только хостнем.. сунулся, а там все еще все бинарное.... (((((

**Comment by ekorneechev** [comment]
Kamino closed and cloned this issue to [MyConnector/MyConnector](https://github.com/MyConnector/MyConnector/issues/2)
